#! /bin/sh
#
# Example panel for LemonBoy's bar

while read -r line ; do
    case $line in
        S*)
            sys_infos="%{r}${line#?}%{F-}"
            ;;
        T*)
	    title="%{A:launcher:} %{F#FFcd546c}  %{F-}bspwm %{A}"
            ;;
        W*)
            wm_infos="%{c}"
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [OFU]*)
                        # active desktop
			wm_infos="$wm_infos%{F#FFcd546c} ${name} %{F-}"
                        ;;
                    o*)
                        # inactive but occupied desktop
                        wm_infos="$wm_infos%{F#FFcccccc} ${name} %{F-}"
                        ;;
                    f*)
                        # inactive desktop
                        wm_infos="$wm_infos%{F#FF666666} ${name} %{F-}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos%{F#FFef545f}% ${name} %{F-}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "$title$wm_infos$sys_infos"
done
